# Generated by Django 2.1.3 on 2018-11-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SysFunction',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('sequence', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
    ]
